baseURL = "https://gmrico.github.io/"
languageCode = "en-us"
title = "Rico Blog"
theme = "PaperMod"

[params]
defaultTheme = "dark"
ShowReadingTime = true
ShowCodeCopyButtons = true
comments = true
ShareButtons = [ "linkedin", "twitter" ]

  [params.homeInfoParams]
  Title = "Hi there wave"
  Content = "Can be Info, links, about..."

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[outputs]
home = [ "HTML", "RSS", "JSON" ]


[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 10

